really-quiet=yes

msg-level=all=status,cplayer=no,ffmpeg=no,ao=no,demuxer=no

term-playing-msg=----------------------------------------\nNOW PLAYING: ${media-title}\n----------------------------------------

term-status-msg=[${playback-time/full} / ${duration/full}] ${percent-pos}%

